# Generated by Django 3.1.14 on 2023-03-18 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20230309_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='instagram',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telegram',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Telegram'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='vk',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='VK'),
        ),
    ]
