# Generated by Django 3.1.14 on 2023-03-20 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20230319_0239'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='mail',
            field=models.CharField(max_length=40, unique=True, verbose_name='Mail'),
        ),
    ]
