# Generated by Django 3.1.14 on 2023-03-21 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20230320_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pk_user', models.IntegerField(verbose_name='PK пользователя')),
                ('user', models.CharField(max_length=40, verbose_name='Адрес пользователя')),
                ('data', models.DateTimeField(verbose_name='Дата входв')),
            ],
        ),
    ]
