# Generated by Django 3.1.14 on 2023-04-04 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20230402_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mail',
            field=models.CharField(max_length=40, null=True, unique=True, verbose_name='Mail'),
        ),
    ]
