from django.db import models

# Create your models here.
class Objects(models.Model):
    tower = models.CharField(max_length=150)
    sub_tower = models.CharField(max_length=150)
    type_operation = models.CharField(max_length=150)
    address = models.CharField(max_length=150)
    property_type = models.CharField(max_length=60, verbose_name="Тип недвижимости")
    status = models.CharField(max_length=60, verbose_name="Статус")
    wtcw = models.CharField(max_length=60, verbose_name="С кем связь")
    number_phone = models.CharField(max_length=60, verbose_name="Номер телефона")
    amount_remuneration = models.IntegerField(verbose_name="Размер вознаграждения")
    Appoint_responsible_person = models.CharField(max_length=60, verbose_name="Назначить ответственного", null=True, blank=True)
    price_month = models.IntegerField(verbose_name="месяц", null=True, blank=True)
    price_square_month = models.IntegerField(verbose_name="м²/ месяц", null=True, blank=True)
    price_square_year = models.IntegerField(verbose_name="м²/ год", null=True, blank=True)
    price = models.IntegerField(verbose_name="За все", null=True, blank=True)
    price_metr = models.IntegerField(verbose_name="За м²", null=True, blank=True)
    rooms = models.CharField(max_length=150, verbose_name="Комнат", null=True, blank=True)
    bedrooms = models.CharField(max_length=150, verbose_name="Спален", null=True, blank=True)
    wet_spots = models.CharField(max_length=150, verbose_name="Мокрые точки", null=True, blank=True)
    total_area = models.IntegerField(verbose_name="Общая площадь", null=True, blank=True)
    floor = models.IntegerField(verbose_name="Этаж", null=True, blank=True)
    number_of_floors = models.IntegerField(verbose_name="Этажность", null=True, blank=True)
    duration = models.CharField(max_length=150, verbose_name="Длительность", null=True, blank=True)
    bathroom = models.CharField(max_length=150, verbose_name="Санузел", null=True, blank=True)
    repair = models.CharField(max_length=150, verbose_name="Ремонт", null=True, blank=True)
    cleaning = models.CharField(max_length=150, verbose_name="Клининг", null=True, blank=True)
    communal_apartment = models.CharField(max_length=150, verbose_name="Комуналка", null=True, blank=True)
    vat = models.CharField(max_length=150, verbose_name="НДС", null=True, blank=True)
    prepayment = models.CharField(max_length=150, verbose_name="Предоплата", null=True, blank=True)
    deposit = models.CharField(max_length=150, verbose_name="Залог", null=True, blank=True)
    conveniences = models.CharField(max_length=150, verbose_name="Удобства", null=True, blank=True)
    one_room = models.CharField(max_length=150, verbose_name="1 комната", null=True, blank=True)
    ownership = models.CharField(max_length=150, verbose_name="Право собственности", null=True, blank=True)
    encumbrance = models.CharField(max_length=150, verbose_name="Обременение", null=True, blank=True)
    ready_made_business = models.CharField(max_length=150, verbose_name="Готовый бизнес", null=True, blank=True)
    check_in = models.DateField(verbose_name="Заезд", null=True, blank=True)
    departure = models.DateField(verbose_name="Отъезд", null=True, blank=True)

    gorod_view = models.IntegerField(null=True, blank=True, verbose_name="Вид на город")
    city_view = models.IntegerField(verbose_name="Вид на сити", null=True, blank=True)
    master_bedroom = models.IntegerField(null=True, blank=True, verbose_name="Мастер-спальня")
    furniture = models.IntegerField(null=True, blank=True, verbose_name="Мебель")
    corner = models.IntegerField(null=True, blank=True, verbose_name="Угол")
    kitchen_living = models.IntegerField(null=True, blank=True, verbose_name="Кухня гостиная")
    wardrobe = models.IntegerField(null=True, blank=True, verbose_name="Гардеробная")
    bed = models.IntegerField(null=True, blank=True, verbose_name="Кровать")
    household_appliances = models.IntegerField(null=True, blank=True, verbose_name="Бытовые приборы")
    laundry_room = models.IntegerField(null=True, blank=True, verbose_name="Постирочная")
    shower = models.IntegerField(null=True, blank=True, verbose_name="Душ")
    bath = models.IntegerField(null=True, blank=True, verbose_name="Ванна")
    your_own_farm = models.IntegerField(null=True, blank=True, verbose_name="Свой с/у")
    user = models.IntegerField(verbose_name="Пользователь", null=True, blank=True)
    plan = models.FileField(verbose_name="Планировка", null=True, blank=True)
    pdf = models.FileField(verbose_name="PDF", null=True, blank=True)
    description = models.CharField(max_length=15000,verbose_name="Описание", null=True, blank=True)
    note = models.CharField(max_length=15000,verbose_name="Примечание", null=True, blank=True)

    def __str__(self):
        return str(self.pk)


class Images(models.Model):
    note = models.ForeignKey(Objects,on_delete=models.CASCADE)
    image = models.ImageField(upload_to='obj_img/',null=True,blank=True)

