# Generated by Django 3.1.14 on 2023-03-07 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Objects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tower', models.CharField(max_length=150)),
                ('sub_tower', models.CharField(max_length=150)),
                ('type_operation', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('property_type', models.CharField(max_length=60, verbose_name='Тип недвижимости')),
                ('status', models.CharField(max_length=60, verbose_name='Статус')),
                ('wtcw', models.CharField(max_length=60, verbose_name='С кем связь')),
                ('number_phone', models.CharField(max_length=60, verbose_name='Номер телефона')),
                ('amount_remuneration', models.IntegerField(verbose_name='Размер вознаграждения')),
                ('Appoint_responsible_person', models.CharField(default=None, max_length=60, verbose_name='Назначить ответственного')),
                ('price_month', models.IntegerField(default=None, verbose_name='месяц')),
                ('price_square_month', models.IntegerField(default=None, verbose_name='м²/ месяц')),
                ('price_square_year', models.IntegerField(default=None, verbose_name='м²/ год')),
                ('price', models.IntegerField(default=None, verbose_name='За все')),
                ('price_metr', models.IntegerField(default=None, verbose_name='За м²')),
                ('rooms', models.CharField(default=None, max_length=150, verbose_name='Комнат')),
                ('bedrooms', models.CharField(default=None, max_length=150, verbose_name='Спален')),
                ('wet_spots', models.CharField(default=None, max_length=150, verbose_name='Мокрые точки')),
                ('total_area', models.IntegerField(default=None, verbose_name='Общая площадь')),
                ('duration', models.CharField(default=None, max_length=150, verbose_name='Длительность')),
                ('bathroom', models.CharField(default=None, max_length=150, verbose_name='Санузел')),
                ('repair', models.CharField(default=None, max_length=150, verbose_name='Ремонт')),
                ('cleaning', models.CharField(default=None, max_length=150, verbose_name='Клининг')),
                ('communal_apartment', models.CharField(default=None, max_length=150, verbose_name='Комуналка')),
                ('vat', models.CharField(default=None, max_length=150, verbose_name='НДС')),
                ('prepayment', models.CharField(default=None, max_length=150, verbose_name='Предоплата')),
                ('deposit', models.CharField(default=None, max_length=150, verbose_name='Залог')),
                ('conveniences', models.CharField(default=None, max_length=150, verbose_name='Удобства')),
                ('one_room', models.CharField(default=None, max_length=150, verbose_name='1 комната')),
                ('ownership', models.CharField(default=None, max_length=150, verbose_name='Право собственности')),
                ('encumbrance', models.CharField(default=None, max_length=150, verbose_name='Обременение')),
                ('ready_made_business', models.CharField(default=None, max_length=150, verbose_name='Готовый бизнес')),
                ('check_in', models.DateField(default=None, verbose_name='Заезд')),
                ('departure', models.DateField(default=None, verbose_name='Отъезд')),
            ],
        ),
    ]
