# Generated by Django 3.1.14 on 2023-03-07 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objects',
            name='price',
            field=models.IntegerField(default=0, verbose_name='За все'),
        ),
        migrations.AlterField(
            model_name='objects',
            name='price_metr',
            field=models.IntegerField(default=0, verbose_name='За м²'),
        ),
        migrations.AlterField(
            model_name='objects',
            name='price_month',
            field=models.IntegerField(default=0, verbose_name='месяц'),
        ),
        migrations.AlterField(
            model_name='objects',
            name='price_square_month',
            field=models.IntegerField(default=0, verbose_name='м²/ месяц'),
        ),
        migrations.AlterField(
            model_name='objects',
            name='price_square_year',
            field=models.IntegerField(default=0, verbose_name='м²/ год'),
        ),
        migrations.AlterField(
            model_name='objects',
            name='total_area',
            field=models.IntegerField(default=0, verbose_name='Общая площадь'),
        ),
    ]
