# Generated by Django 3.1.14 on 2023-03-07 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0002_auto_20230308_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objects',
            name='Appoint_responsible_person',
            field=models.CharField(max_length=60, null=True, verbose_name='Назначить ответственного'),
        ),
        migrations.AlterField(
            model_name='objects',
            name='bathroom',
            field=models.CharField(max_length=150, null=True, verbose_name='Санузел'),
        ),
        migrations.AlterField(
            model_name='objects',
            name='bedrooms',
            field=models.CharField(max_length=150, null=True, verbose_name='Спален'),
        ),
        migrations.AlterField(
            model_name='objects',
            name='check_in',
            field=models.DateField(null=True, verbose_name='Заезд'),
        ),
        migrations.AlterField(
            model_name='objects',
            name='cleaning',
            field=models.CharField(max_length=150, null=True, verbose_name='Клининг'),
        ),
        migrations.AlterField(
            model_name='objects',
            name='communal_apartment',
            field=models.CharField(max_length=150, null=True, verbose_name='Комуналка'),
        ),
        migrations.AlterField(
            model_name='objects',
            name='conveniences',
            field=models.CharField(max_length=150, null=True, verbose_name='Удобства'),
        ),
        migrations.AlterField(
            model_name='objects',
            name='departure',
            field=models.DateField(null=True, verbose_name='Отъезд'),
        ),
        migrations.AlterField(
            model_name='objects',
            name='deposit',
            field=models.CharField(max_length=150, null=True, verbose_name='Залог'),
        ),
        migrations.AlterField(
            model_name='objects',
            name='duration',
            field=models.CharField(max_length=150, null=True, verbose_name='Длительность'),
        ),
        migrations.AlterField(
            model_name='objects',
            name='encumbrance',
            field=models.CharField(max_length=150, null=True, verbose_name='Обременение'),
        ),
        migrations.AlterField(
            model_name='objects',
            name='one_room',
            field=models.CharField(max_length=150, null=True, verbose_name='1 комната'),
        ),
        migrations.AlterField(
            model_name='objects',
            name='ownership',
            field=models.CharField(max_length=150, null=True, verbose_name='Право собственности'),
        ),
        migrations.AlterField(
            model_name='objects',
            name='prepayment',
            field=models.CharField(max_length=150, null=True, verbose_name='Предоплата'),
        ),
        migrations.AlterField(
            model_name='objects',
            name='price',
            field=models.IntegerField(null=True, verbose_name='За все'),
        ),
        migrations.AlterField(
            model_name='objects',
            name='price_metr',
            field=models.IntegerField(null=True, verbose_name='За м²'),
        ),
        migrations.AlterField(
            model_name='objects',
            name='price_month',
            field=models.IntegerField(null=True, verbose_name='месяц'),
        ),
        migrations.AlterField(
            model_name='objects',
            name='price_square_month',
            field=models.IntegerField(null=True, verbose_name='м²/ месяц'),
        ),
        migrations.AlterField(
            model_name='objects',
            name='price_square_year',
            field=models.IntegerField(null=True, verbose_name='м²/ год'),
        ),
        migrations.AlterField(
            model_name='objects',
            name='ready_made_business',
            field=models.CharField(max_length=150, null=True, verbose_name='Готовый бизнес'),
        ),
        migrations.AlterField(
            model_name='objects',
            name='repair',
            field=models.CharField(max_length=150, null=True, verbose_name='Ремонт'),
        ),
        migrations.AlterField(
            model_name='objects',
            name='rooms',
            field=models.CharField(max_length=150, null=True, verbose_name='Комнат'),
        ),
        migrations.AlterField(
            model_name='objects',
            name='total_area',
            field=models.IntegerField(null=True, verbose_name='Общая площадь'),
        ),
        migrations.AlterField(
            model_name='objects',
            name='vat',
            field=models.CharField(max_length=150, null=True, verbose_name='НДС'),
        ),
        migrations.AlterField(
            model_name='objects',
            name='wet_spots',
            field=models.CharField(max_length=150, null=True, verbose_name='Мокрые точки'),
        ),
    ]
