# Generated by Django 3.1.14 on 2023-03-13 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0004_auto_20230310_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='objects',
            name='photo',
            field=models.ImageField(default=1, upload_to='obj_img/'),
            preserve_default=False,
        ),
    ]
