# Generated by Django 3.1.14 on 2023-03-13 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0005_objects_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objects',
            name='photo',
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='obj_img/')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.objects')),
            ],
        ),
    ]
