# Generated by Django 3.1.14 on 2023-03-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0008_objects_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='objects',
            name='number_of_floors',
            field=models.IntegerField(blank=True, null=True, verbose_name='Этажность'),
        ),
    ]
