# Generated by Django 3.1.14 on 2023-03-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0009_objects_number_of_floors'),
    ]

    operations = [
        migrations.AddField(
            model_name='objects',
            name='user',
            field=models.IntegerField(blank=True, null=True, verbose_name='Пользователь'),
        ),
    ]
