# Generated by Django 3.1.14 on 2023-03-17 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0012_objects_your_own_farm'),
    ]

    operations = [
        migrations.AddField(
            model_name='objects',
            name='description',
            field=models.CharField(blank=True, max_length=15000, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='objects',
            name='note',
            field=models.CharField(blank=True, max_length=15000, null=True, verbose_name='Примечание'),
        ),
        migrations.AddField(
            model_name='objects',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='PDF'),
        ),
        migrations.AddField(
            model_name='objects',
            name='plan',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Планировка'),
        ),
    ]
