# Generated by Django 3.1.14 on 2023-03-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0013_auto_20230318_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objects',
            name='rooms',
            field=models.CharField(blank=True, choices=[('0', 'Female'), ('1', 'male')], max_length=150, null=True, verbose_name='Комнат'),
        ),
    ]
