# Generated by Django 3.1.14 on 2023-03-19 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0014_auto_20230319_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objects',
            name='rooms',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Комнат'),
        ),
    ]
