# Generated by Django 3.1.14 on 2023-03-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0015_auto_20230320_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='objects',
            name='x',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='objects',
            name='y',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
