# Generated by Django 4.1.7 on 2023-04-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0018_alter_images_id_alter_objects_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objects',
            name='total_area',
            field=models.IntegerField(blank=True, null=True, verbose_name='Общая площадь'),
        ),
    ]
